// THIS FILE IS GENERATED BY pem2def.py. DONT EDIT.

#ifndef MBEDTLS_EXAMPLE_TRUSTED_CERTS_H
#define MBEDTLS_EXAMPLE_TRUSTED_CERTS_H

#define mozilla_ca_bundle \
"##\r\n"\
"## Bundle of CA Root Certificates\r\n"\
"##\r\n"\
"## Certificate data from Mozilla as of: Wed Nov  2 04:12:05 2016 GMT\r\n"\
"##\r\n"\
"## This is a bundle of X.509 certificates of public Certificate Authorities\r\n"\
"## (CA). These were automatically extracted from Mozilla's root certificates\r\n"\
"## file (certdata.txt).  This file can be found in the mozilla source tree:\r\n"\
"## https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt\r\n"\
"##\r\n"\
"## It contains the certificates in PEM format and therefore\r\n"\
"## can be directly used with curl / libcurl / php_curl, or with\r\n"\
"## an Apache+mod_ssl webserver for SSL client authentication.\r\n"\
"## Just configure this file as the SSLCACertificateFile.\r\n"\
"##\r\n"\
"## Conversion done with mk-ca-bundle.pl version 1.27.\r\n"\
"## SHA256: 17e2a90c8a5cfd6a675b3475d3d467e1ab1fe0d5397e907b08206182389caa08\r\n"\
"##\r\n"\
"\r\n"\
"\r\n"\
"GlobalSign Root CA\r\n"\
"==================\r\n"\
"-----BEGIN CERTIFICATE-----\r\n"\
"MIIFsTCCA5mgAwIBAgIJAJPNX663s8CNMA0GCSqGSIb3DQEBCwUAMG8xCzAJBgNV\r\n"\
"BAYTAlVTMREwDwYDVQQIDAh2aXJnaW5pYTETMBEGA1UEBwwKYmxhY2tzYnVyZzEL\r\n"\
"MAkGA1UECgwCdnQxCzAJBgNVBAsMAnZ0MQswCQYDVQQDDAJ2dDERMA8GCSqGSIb3\r\n"\
"DQEJARYCdnQwHhcNMTcxMTI2MDIwMTU1WhcNMTgxMTI2MDIwMTU1WjBvMQswCQYD\r\n"\
"VQQGEwJVUzERMA8GA1UECAwIdmlyZ2luaWExEzARBgNVBAcMCmJsYWNrc2J1cmcx\r\n"\
"CzAJBgNVBAoMAnZ0MQswCQYDVQQLDAJ2dDELMAkGA1UEAwwCdnQxETAPBgkqhkiG\r\n"\
"9w0BCQEWAnZ0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5H2TR3Ca\r\n"\
"MM0TxY9a7UUK7U/VmYmOEcK0LkOE2Baz4Z2wZmj1ZQBjMbPQ4v/6dbjYOQ9flQff\r\n"\
"ugmd+M6dVf2x0e5WzTQh52mI+Tv9UbHJ2eJe+yirXLdDTwUhurzs5AEvZvKvjxoh\r\n"\
"bk8Fg181mU9d+T4xK1USgXsMpKbJjRqCjJCiZTvvAikvmPA0XEBmxQto+jYrc2Ns\r\n"\
"ULVloHntS/pJ076MgtBywTFtcSstc/Kges6tzwY+2ic77+sfWBE0daLS3KJ/njqo\r\n"\
"rsuCMU9czrGRC7fmoOugO6V+9brOf+Zvxoj7UaPr8uKL+xUzEpsVJudSA1wU2ki9\r\n"\
"psxXXei9FO388g7m8X6/K6CtMCBtwaJpKICgVXVZGZKUhjcFDpd3WFGZfp4LePqy\r\n"\
"KevTRNYyrWawKOPQz2JazEj8KLXb+goKYyrUHu6GScXQZdUFRa93tTkBotlSRJvt\r\n"\
"o45sp3rXR2u3MtKEtFpp9NM1jThF6JdBgvouz4hf2uk5Hy1avwVUDy53jMEHUeU7\r\n"\
"jRoVbOzAnlsT5yVQrjk4qojCgOmQhv7jA3cxjB7SV0X+g1NJiIv0354QqFWfTHpN\r\n"\
"QK2lPuxucLdXzT/GPCG2aMymdRiqmT03iIrQqnNkVIcOlxGc7bNURxuOP8NBrqj/\r\n"\
"Q+8BA/c5zp8ekysAwEUAutErlfjxK+HNZy0CAwEAAaNQME4wHQYDVR0OBBYEFOKN\r\n"\
"NLlAxUOtEQVHLB+tFYOeCOs5MB8GA1UdIwQYMBaAFOKNNLlAxUOtEQVHLB+tFYOe\r\n"\
"COs5MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAJ5ZdKh1G+RNr1IK\r\n"\
"GDQUPDrCZF39/4m5UJ4HHT+5ob/w1M5IgQJ/nKqkvaZKkApul5jlTPQ1L8zJAqvW\r\n"\
"eA/O9vPrQ+SY1mUvDfrcxFFAIyo8q0ESAGfsaoRGLs0iACJ9kbRyyXkFu6U6GhZE\r\n"\
"la0WMbUeqwqak7Ht1U17s4wL0kWh+Z5GLFvjkpwJiKpcMXW1UAmxHrf6/oI2gxLb\r\n"\
"2ywueBj47X+MgigHK9rhF2lB42Iq6J9Vkqw9ent01DhUmE3sIhF35URyapC3AC0y\r\n"\
"6z3dUrawQAAaQYsI4f4j3luOitrs9HBJWtSw4uRG2LY8FBITpmKlPlzUfZqAJJRT\r\n"\
"ij3d8RfAb5h4ZHKMVULHfbPN0WLUxKQTtRQaIOqIM3f2s8eDqZlmhUb5JgpnB5p3\r\n"\
"RElJanHJucCF8lABHT7b6HbjbnMRwjIzS06SSEucltUxNERM3MW9FAiDXDGNlXFY\r\n"\
"Y8upZTw5QpOPR3DG1gySC0CBllnz/WRGws0+e4+TO3n9DS4hWHjgD/9m9gD8CTns\r\n"\
"OZymDzlfjruxhKKmWVHFLgZaNdDY+rehmpVO6OBmYNncprpqXsY4Y9cwThqYe/Fr\r\n"\
"k+8Jz4sJW4kG1Yc4t39jVbx8z5smuk1MF/kfLgHFnKYXoo6oFpJ0dHqQmjSJSl0j\r\n"\
"CptJI37syk9W1fpZxRyx04csGElP\r\n"\
"-----END CERTIFICATE-----\r\n"
/*"-----BEGIN CERTIFICATE-----\r\n"\
"MIIFsTCCA5mgAwIBAgIJAKJYzgQsPhmlMA0GCSqGSIb3DQEBCwUAMG8xCzAJBgNV\r\n"\
"BAYTAlVTMREwDwYDVQQIDAh2aXJnaW5pYTETMBEGA1UEBwwKYmxhY2tzYnVyZzEL\r\n"\
"MAkGA1UECgwCdnQxCzAJBgNVBAsMAnZ0MQswCQYDVQQDDAJ2dDERMA8GCSqGSIb3\r\n"\
"DQEJARYCdnQwHhcNMTcxMTIxMDAwMTU1WhcNMTgxMTIxMDAwMTU1WjBvMQswCQYD\r\n"\
"VQQGEwJVUzERMA8GA1UECAwIdmlyZ2luaWExEzARBgNVBAcMCmJsYWNrc2J1cmcx\r\n"\
"CzAJBgNVBAoMAnZ0MQswCQYDVQQLDAJ2dDELMAkGA1UEAwwCdnQxETAPBgkqhkiG\r\n"\
"9w0BCQEWAnZ0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAoA3rqGFN\r\n"\
"STCmPEJi3kKJ1Hh6+BXAQ40dAO9y1R/Vimy2JJV5DRmrk+aCjJ5H/tlqZ3hdCJbq\r\n"\
"9BxNHk0H+1lMftA0AfalX7Uvl2VWCgGGeT+I/32H4KzI62IN7wx7NjRPYMG5ICuY\r\n"\
"rXNS8JpQOnKgx081bxPjUuS824KSUJeXc1NnhOSDpLAz3f0600tKl9lIIaW0U9Uh\r\n"\
"tND25YCc0GE3NXIoIbE3HXrMAnvaru2uakROr7AFiQYYYEb0i5BCPCf6VU2jW49U\r\n"\
"ortCwdu4ytn78HKebhgwX8fGy5JS5sbYyK19EqVpasHS+A3RPq7cyjDTRcIo7gOt\r\n"\
"f7VnyACtOYCoe3XuH9KMCMlE5ERIe3yhh67lMt46yggElnHMcWWQY7/LVXPwinks\r\n"\
"2pYybGsiq/UcWHwtbQBcD40RZ/IEGL6ATnJwApe+nESDMKsk8jpQGLo4ClTyTPLq\r\n"\
"K1czdLAq//0N++iKoY7mxTR89PsPWmagsV8jWCRV5EQ6nuJm1YjofQLAPhgLmMwx\r\n"\
"Z0FJoc4l79rEuZGBJiN3wiAc2yJgKVAjd3wQBKpFRPqS2b8lWCcBWfpyzBHIfcdL\r\n"\
"Ya8hl+nRl8sDymYn4heHA+Hfo8r2BSTolSODsFvYXDOhhrunNZObnPHPxNQv4wMx\r\n"\
"MMMv6XpaKuCvUZdHSyj+rSjV/Jhucwab4xMCAwEAAaNQME4wHQYDVR0OBBYEFHax\r\n"\
"k2CFskV8KB5w1BQ4twgkmMfGMB8GA1UdIwQYMBaAFHaxk2CFskV8KB5w1BQ4twgk\r\n"\
"mMfGMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAJUD0zJze51pFPFS\r\n"\
"YZeyTdCiB1N4egbo6HThmWvOH1tsYoZA8IEzeJy/tqLbonx2Fg1NAj75O35b96wH\r\n"\
"lHtYPEhsHH1nY57LL2jD4pmLUvOwI1MvGHARvUkoKCcihdF4dh4KCmyZczEllCHH\r\n"\
"RAMP6VWnwEcUaFsGjTnB14HQhDTEYWJrp8c0Cn1QARw/iexbStQFclHo4ZPwN4Lz\r\n"\
"RVwsnjJd0sK5jc2erofRh/0JJcYeIcBfD08bR6dGWw0pl8UznvrbLiOiYzKUm+VS\r\n"\
"dFr1s8YevJi0Tpn6WSGwoJdwktVg1dLpXS544kTTEs90BnhQVJUyUqkoLMLSp2sM\r\n"\
"66YOrGtWMI95EIDssww+8vX2t7IfCGPpYO1wr62mrUiRqHyCEmLs9rld6iuEY7tC\r\n"\
"8Rr1XCEsR63ySnOXQScGRJMPpvdnOzXzbuKne1ljGSuckTf6jS3RUSQIiL9NizXR\r\n"\
"LNG17NABoZa2v70zDvfNjrBcqfoJ7+mocnSypUAYRzMsji0xmHRnuqxY1OOs5LR3\r\n"\
"yad00+nbqe4IVJni57ynxXM5B5BcaQP0wHfJ1oxRkpXVYHg45pXiPs+IpEO7Xaxm\r\n"\
"nuoiuMl3SWZ6bHyPs0EVGCaBv7PgGBNLzZoSJrqjaxWYwxQhefTekdUH1bjjmt1w\r\n"\
"MCT6EggokZWGEhkRAMh/hUoSZWYQ==\r\n"\
"-----END CERTIFICATE-----\r\n"\
*/
#endif
